### ISSUE TITLE
Port this feature to Recode?

### ISSUE THREAD

**Issue by kianmeng** [jakub-gonet/alias_sorter#1]
Hey, this looks like a neat feature, is it possible to port this to https://github.com/hrzndhrn/recode?

**Comment by jgonet** [comment]
I had some experiments with sourceror (you can see them in `livebooks/`). For now, I don't plan on doing so, this package is highly experimental and tailored for my use-cases. From what I'm seeing, there's already [sorter module](https://github.com/hrzndhrn/recode/blob/2aa844a96c52a5cd6eddf790f77755e0973d50e9/lib/recode/task/alias_order.ex) there.
